model:
  config_path: "config/coe-tiny-hf-v2"
  trust_remote_code: true
  output_dir: "./output/coe-v7-e2-t1-h8-b8"
  config:
    use_expert_communication: false
    num_experts_per_tok: 2
    inner_iter: 1
    num_hidden_layers: 8

training:
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  num_train_epochs: 3
  learning_rate: 5.0e-5
  max_grad_norm: 1.0
  weight_decay: 0.01
  save_steps: 1000
  logging_steps: 1
  fp16: false
  prediction_loss_only: true

optimizer:
  type: "AdamW"
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8

tokenizer:
  path: "config/coe-tiny-hf-v2"
  max_length: 512
  padding: "max_length"
  return_tensors: "pt"

data:
  name: "wikitext"
  config: "wikitext-103-v1"
  split: "train"
  sample_size: 240000
  preprocessing:
    min_char_length: 2000
    truncation: true
    max_length: 512
    padding: "max_length"
    return_tensors: "pt"
    remove_columns: true

scheduler:
  type: "linear"
  warmup_steps: 500

evaluation:
  do_eval: true
  eval_steps: 10
  val_size: 32
  per_device_eval_batch_size: 8
  load_best_model_at_end: true

checkpointing:
  save_total_limit: 3
  save_strategy: "steps"